apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-world
spec:
  replicas: 15
  selector:
    name: dev
  template:
    metadata:
      name: myapp
      labels:
        name: dev
    spec:
      containers:
        - name: imran-container
          image: nigelpoulton/pluralsight-docker-ci:latest
          ports:
            - containerPort: 8080
